import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import { createElement } from 'react';
import type { AuditEvent } from '@/types';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#1a1a1a' },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 8 },
  meta: { fontSize: 9, color: '#666', marginBottom: 20 },
  body: { lineHeight: 1.6, marginBottom: 30 },
  signatureSection: { marginTop: 20, borderTop: '1px solid #ddd', paddingTop: 20 },
  signatureBlock: { marginBottom: 15 },
  signatureLabel: { fontSize: 9, color: '#666', marginBottom: 4 },
  signatureImage: { width: 150, height: 50, marginBottom: 4 },
  auditSection: { marginTop: 30, borderTop: '1px solid #ddd', paddingTop: 15 },
  auditTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 8 },
  auditRow: { fontSize: 8, color: '#666', marginBottom: 3 },
});

interface PdfProps {
  title: string;
  contentText: string;
  signatures: Array<{ role: string; data: string; name?: string; date: string }>;
  auditEvents: AuditEvent[];
}

export function ContractPdf({ title, contentText, signatures, auditEvents }: PdfProps) {
  return createElement(Document, {},
    createElement(Page, { size: 'A4', style: styles.page },
      createElement(Text, { style: styles.title }, title),
      createElement(Text, { style: styles.meta }, `Generated by SignCraft · ${new Date().toLocaleDateString()}`),
      createElement(Text, { style: styles.body }, contentText),

      createElement(View, { style: styles.signatureSection },
        ...signatures.map((sig, i) =>
          createElement(View, { key: i, style: styles.signatureBlock },
            createElement(Text, { style: styles.signatureLabel }, sig.role === 'signer' ? 'Signer' : 'Countersigner'),
            sig.data.startsWith('data:')
              ? createElement(Image, { style: styles.signatureImage, src: sig.data })
              : createElement(Text, {}, sig.data),
            createElement(Text, { style: styles.signatureLabel }, `Signed: ${new Date(sig.date).toLocaleString()}`),
          )
        ),
      ),

      createElement(View, { style: styles.auditSection },
        createElement(Text, { style: styles.auditTitle }, 'Audit Trail'),
        ...auditEvents.map((event, i) =>
          createElement(Text, { key: i, style: styles.auditRow },
            `${new Date(event.created_at).toLocaleString()} — ${event.event_type} ${event.ip_address ? `(IP: ${event.ip_address})` : ''}`
          )
        ),
      ),
    )
  );
}
